r"""Emit the interpreter paths this project actually needs, for IDE indexing.

PyCharm cannot resolve `pxr`, `isaacsim.*` or `omni.*` from Project Structure marks,
for two reasons that are easy to hit and hard to see:

  1. The importable root is each *extension folder*, not its parent. Subdirectories of
     `exts/` and `extscache/` are named `isaacsim.storage.native` and
     `carb.audio-0.1.0+f9bf0dda.wx64.r.cp312` -- dots and plus signs, never legal
     package names. Marking `exts/` as Sources or Namespace Packages cannot work.

  2. `python_packages/isaacsim/__init__.py` is a *regular* package. Putting it on the
     path shadows the PEP 420 `isaacsim` namespace and blocks every extension branch
     from merging in. NVIDIA's own generator strips it from the IDE list for exactly
     this reason, while `sitecustomize.py` keeps it at runtime.

So the paths have to go on the interpreter, not into Project Structure. The full list
NVIDIA generates has 647 entries; this project imports about ten things, so that is what
this emits.

    python isaac\tools\ide_paths.py            list the paths and what needs them
    python isaac\tools\ide_paths.py --write    write them as a .pth on the interpreter
    python isaac\tools\ide_paths.py --remove   delete that .pth

After --write, run *File -> Invalidate Caches and Restart* in PyCharm.

`extscache` directory names carry version stamps, so re-run --write after any Kit SDK
bump. If the source list is stale, regenerate it first from the isaacsim repo:

    repo.bat generate_vscode_settings -c release

Exit code 0 if every import resolved, 1 otherwise.
"""

from __future__ import annotations

import argparse
import ast
import io
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _bootstrap import repo_root  # noqa: E402

PTH_NAME = "rendergap_paths.pth"

# Top-level namespaces that come from Isaac/Kit rather than the stdlib or pip.
KIT_NAMESPACES = ("isaacsim", "omni", "carb", "pxr", "usdrt", "warp", "omni.isaac")


# --------------------------------------------------------------------------
# Locating the Isaac build
# --------------------------------------------------------------------------
def find_isaac_path() -> str:
    """ISAAC_PATH if the env wrapper set it, else ISAACSIM_ROOT out of env\\local.bat."""
    value = os.environ.get("ISAAC_PATH")
    if value and os.path.isdir(value):
        return os.path.normpath(value)

    local = os.path.join(repo_root(), "env", "local.bat")
    if os.path.exists(local):
        text = io.open(local, encoding="utf-8", errors="replace").read()
        m = re.search(r'^\s*set\s+"?ISAACSIM_ROOT=([^"\r\n]+)"?', text, re.M | re.I)
        if m and os.path.isdir(m.group(1)):
            return os.path.normpath(m.group(1))

    raise SystemExit(
        "Could not locate the Isaac Sim build.\n"
        "Set ISAAC_PATH, or put ISAACSIM_ROOT in env\\local.bat "
        "(copy env\\local.bat.example)."
    )


def isaacsim_repo_root(isaac_path: str) -> str:
    """<repo>/_build/<platform>/<config> -> <repo>."""
    return os.path.normpath(os.path.join(isaac_path, "..", "..", ".."))


# --------------------------------------------------------------------------
# The candidate roots: NVIDIA's generated list
# --------------------------------------------------------------------------
def load_candidate_roots(sim_repo: str) -> list[str]:
    settings = os.path.join(sim_repo, ".vscode", "settings.json")
    if not os.path.exists(settings):
        raise SystemExit(
            f"Not found: {settings}\n"
            "It is generated by the build and gitignored. Produce it with:\n"
            "    repo.bat generate_vscode_settings -c release"
        )

    text = io.open(settings, encoding="utf-8").read()
    # JSONC: // comments and a trailing comma before ']'. Regex, not json.load.
    block = re.search(r'"python\.analysis\.extraPaths"\s*:\s*\[(.*?)\]', text, re.S)
    if not block:
        raise SystemExit(f"No python.analysis.extraPaths in {settings}")

    roots = []
    for rel in re.findall(r'"([^"]+)"', block.group(1)):
        if "/release/" not in rel:
            continue  # debug-config entries
        if "python_packages" in rel:
            continue  # reason 2 in the module docstring
        full = os.path.normpath(os.path.join(sim_repo, rel))
        if os.path.isdir(full):
            roots.append(full)
    return roots


# --------------------------------------------------------------------------
# What this project imports
# --------------------------------------------------------------------------
def project_imports(start: str) -> tuple[set[str], set[str]]:
    """Kit/Isaac imports found in the project's Python files.

    Returns (modules, probes).

    `modules` are real module paths -- from `import X` and the `X` of
    `from X import ...`. Only these are worth reporting on.

    `probes` adds `X.Y` for every `from X import Y`, because `Y` is often a submodule
    (``from pxr import Gf``) and resolving the deeper name is what distinguishes a real
    package from the namespace portion that every extension folder shares. When `Y` is
    just a class or function the probe simply misses, which is why probes are never
    reported as failures.
    """
    modules: set[str] = set()
    probes: set[str] = set()
    for dirpath, dirnames, filenames in os.walk(start):
        dirnames[:] = [d for d in dirnames if d not in ("__pycache__", "_assets", ".git")]
        for name in filenames:
            if not name.endswith(".py"):
                continue
            path = os.path.join(dirpath, name)
            # utf-8-sig: PyCharm writes a BOM by default on Windows.
            src = io.open(path, encoding="utf-8-sig", errors="replace").read()
            try:
                tree = ast.parse(src, filename=path)
            except SyntaxError as exc:
                print(f"  [skip] {path}: {exc}")
                continue
            for node in ast.walk(tree):
                if isinstance(node, ast.Import):
                    for alias in node.names:
                        modules.add(alias.name)
                elif isinstance(node, ast.ImportFrom) and node.level == 0 and node.module:
                    modules.add(node.module)
                    for alias in node.names:
                        probes.add(f"{node.module}.{alias.name}")

    def kit(names: set[str]) -> set[str]:
        return {n for n in names if n.split(".")[0] in KIT_NAMESPACES}

    return kit(modules), kit(probes)


def provides(root: str, module: str) -> bool:
    """True only for a REGULAR package or a module file.

    A bare directory match is worthless here: `isaacsim/` exists in all 149 extension
    folders as a PEP 420 namespace portion, so matching directories would select
    everything.
    """
    base = os.path.join(root, *module.split("."))
    return os.path.isfile(os.path.join(base, "__init__.py")) or os.path.isfile(base + ".py")


def has_namespace_dir(root: str, module: str) -> bool:
    """The module exists under this root as a PEP 420 namespace portion."""
    return os.path.isdir(os.path.join(root, *module.split(".")))


def resolve(modules: set[str], probes: set[str], roots: list[str]) -> tuple[list[str], list[str], list[str]]:
    """Select the roots needed, and classify the real modules.

    Returns (selected_roots, namespace_only, unresolved).
    """
    selected: set[str] = set()
    for name in sorted(modules | probes):
        selected.update(r for r in roots if provides(r, name))
    selected_list = sorted(selected)

    namespace_only: list[str] = []
    unresolved: list[str] = []
    for module in sorted(modules):
        if any(provides(r, module) for r in selected_list):
            continue
        # No regular package, but a selected root still carries the namespace
        # branch -- which is all a namespace package ever has.
        if any(has_namespace_dir(r, module) for r in selected_list):
            namespace_only.append(module)
        else:
            unresolved.append(module)
    return selected_list, namespace_only, unresolved


# --------------------------------------------------------------------------
# The .pth
# --------------------------------------------------------------------------
def pth_path(isaac_path: str) -> str:
    return os.path.join(isaac_path, "kit", "python", "Lib", "site-packages", PTH_NAME)


def main() -> int:
    ap = argparse.ArgumentParser(description="Emit IDE interpreter paths for this project.")
    ap.add_argument("--write", action="store_true", help="Write the paths as a .pth on the Kit interpreter.")
    ap.add_argument("--remove", action="store_true", help="Delete that .pth.")
    args = ap.parse_args()

    isaac_path = find_isaac_path()
    target = pth_path(isaac_path)

    if args.remove:
        if os.path.exists(target):
            os.remove(target)
            print(f"[ide_paths] removed {target}")
        else:
            print(f"[ide_paths] nothing to remove at {target}")
        return 0

    sim_repo = isaacsim_repo_root(isaac_path)
    roots = load_candidate_roots(sim_repo)
    modules, probes = project_imports(os.path.join(repo_root(), "isaac"))
    selected, namespace_only, unresolved = resolve(modules, probes, roots)

    print(f"[ide_paths] isaac build     : {isaac_path}")
    print(f"[ide_paths] candidate roots : {len(roots)}  (from .vscode/settings.json)")
    print(f"[ide_paths] project imports : {len(modules)} module names")
    print(f"[ide_paths] roots required  : {len(selected)}\n")

    for root in selected:
        needed_by = sorted(n for n in (modules | probes) if provides(root, n))
        print(f"  {root}")
        print(f"      {', '.join(needed_by)}")

    if namespace_only:
        print("\n[ide_paths] namespace-only (covered, no __init__.py by design):")
        print(f"  {', '.join(namespace_only)}")

    if "isaacsim" in namespace_only or "isaacsim" in unresolved:
        print(
            "\n  Note: `from isaacsim import SimulationApp` will still show unresolved.\n"
            "  SimulationApp is re-exported by python_packages/isaacsim/__init__.py, a\n"
            "  REGULAR package -- and putting that path on the interpreter would shadow the\n"
            "  isaacsim namespace and break isaacsim.core.* and isaacsim.storage.* instead.\n"
            "  NVIDIA excludes it for the same reason. It runs fine; only the IDE squiggles."
        )

    if unresolved:
        print("\n[ide_paths] NOT resolved to any root:")
        for module in unresolved:
            print(f"  {module}")

    if args.write:
        os.makedirs(os.path.dirname(target), exist_ok=True)
        with io.open(target, "w", encoding="utf-8", newline="\n") as fh:
            fh.write("\n".join(selected) + "\n")
        print(f"\n[ide_paths] wrote {len(selected)} paths -> {target}")
        print("[ide_paths] now run: File -> Invalidate Caches and Restart")
    else:
        print(f"\n[ide_paths] dry run. --write to install as {target}")

    return 1 if unresolved else 0


if __name__ == "__main__":
    sys.exit(main())
