// Copyright Epic Games, Inc. All Rights Reserved.

#include "RenderGapBenchGameMode.h"

#include "CineCameraActor.h"
#include "CineCameraComponent.h"
#include "Engine/World.h"
#include "EngineUtils.h"
#include "GameFramework/PlayerController.h"
#include "USDStageActor.h"

DEFINE_LOG_CATEGORY_STATIC(LogRenderGapBench, Log, All);

ARenderGapBenchGameMode::ARenderGapBenchGameMode()
{
	PrimaryActorTick.bCanEverTick = true;
	PrimaryActorTick.bStartWithTickEnabled = true;
}

void ARenderGapBenchGameMode::StartPlay()
{
	Super::StartPlay();
	TryBindCamera();
}

void ARenderGapBenchGameMode::Tick(float DeltaSeconds)
{
	Super::Tick(DeltaSeconds);

	if (bBound || bGaveUp)
	{
		return;
	}

	Elapsed += DeltaSeconds;

	if (TryBindCamera())
	{
		return;
	}

	if (Elapsed > ResolveTimeoutSeconds)
	{
		bGaveUp = true;
		SetActorTickEnabled(false);
		UE_LOG(LogRenderGapBench, Error,
			TEXT("Gave up after %.1fs waiting for '%s' to be generated by a UsdStageActor. ")
			TEXT("The render will use the default pawn's view and the frame will not match Isaac."),
			Elapsed, *CameraPrimPath);
	}
}

bool ARenderGapBenchGameMode::TryBindCamera()
{
	UWorld* World = GetWorld();
	if (!World)
	{
		return false;
	}

	APlayerController* PlayerController = World->GetFirstPlayerController();
	if (!PlayerController)
	{
		return false;
	}

	for (TActorIterator<AUsdStageActor> It(World); It; ++It)
	{
		USceneComponent* Component = It->GetGeneratedComponent(CameraPrimPath);
		if (!Component)
		{
			continue;
		}

		// GetGeneratedComponent can hand back the spawned actor's root rather than the
		// camera component itself, exactly as FUsdGeomCameraTranslator has to allow for.
		AActor* CameraActor = Component->GetOwner();
		if (!Cast<ACineCameraActor>(CameraActor))
		{
			continue;
		}

		PlayerController->SetViewTarget(CameraActor);

		bBound = true;
		SetActorTickEnabled(false);
		UE_LOG(LogRenderGapBench, Display,
			TEXT("View target bound to '%s' (actor '%s') after %.2fs."),
			*CameraPrimPath, *CameraActor->GetName(), Elapsed);
		return true;
	}

	return false;
}
